naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/blog.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: lfor1L7Hwpv7F4u9_0cG
    secret: PqUDHmA5qu